export const staticText = {
    jobDashboard: "Job Board",
    jobsDashboard: "Jobs Board",
    jobList: "Available position at",
    jobsList: "Available positions at",
    newJob: "New Job",
    email: "Email",
    password: "Password",
    title: "Title",
    description: "Description",
    login: "Login",
    loginError: "Login failed",
    submit: "Submit",
    home: "Home",
    addJob: "Add Job",
    logout: "Logout",
}